[tool.poetry]
name = "SPIMprep"
version = "0.1.0"
description = ""
authors = ["Ali Khan <alik@robarts.ca>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
snakemake = "<8.0.0"
pulp = "2.7.0"
snakebids = {git = "https://github.com/khanlab/snakebids", rev = "8acbd9f"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
