[tool.poetry]
name = "bigstitcher-smk"
version = "0.1.0"
description = ""
authors = ["Ali Khan <alik@robarts.ca>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
snakemake = "^8.4.2"
snakemake-storage-plugin-gcs = "^0.1.3"
tifffile = "^2023.12.9"
xmltodict = "^0.13.0"
snakebids = "^0.10.0"
basicpy = "^1.1.0"
snakemake-executor-plugin-slurm = "^0.1.5"
snakemake-storage-plugin-fs = "^0.1.5"
npy2bdv = "^1.0.8"
zarr = "^2.16.1"
jax = "0.4.23" 
jaxlib = "0.4.23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
